version: '3.9'
name: 'quote_generator'
services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app
      - /usr/app/node_modules

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./front:/usr/src/app
      - /usr/app/node_modules
